### ISSUE TITLE
Unable to see rest of message with audio file

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-mac#216] opened 2023-11-15 15:39 UTC
**Task**

As per the image below, I am unable to read the rest of the message when an audio file is attached.

![Image](https://github.com/stakwork/sphinx-mac/assets/142233216/001b4773-25cc-40c1-968d-2c179924d3b4)

**Comment by tomastiminskas** [comment] 2023-11-16 12:53
@uncleJim21 Let me take this since I know where the issue is and I can easily fix it so you can stay focused on sphinx v2

**Comment by tomastiminskas** [comment] 2023-11-16 13:21
@tomsmith8 It's fixed. it will be included in next release going out today or tomorrow

**Closed** 2023-11-23 18:18 UTC
Labels: bug
